version: '3'
services:
  angular-ui:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "4201:4201"
    container_name: orion.admin.primefaces.v1.0.1
    volumes:
      - ./
      - /usr/src/app/node_modules
