import { SpecialOfferProduct } from "./special-offer-product.model";
import { UnitMeasure } from "./unit-measure";
import { ProductSubcategory } from "./product-subcategory.model";
import { ProductModel } from "./product-model.model";
import { BillOfMaterials } from "./bill-of-materials.model";
import { ProductDocument } from "./product-document.model";
import { ProductInventory } from "./product-inventory.model";
import { ProductListPriceHistory } from "./product-list-price-history.model";
import { ProductProductPhoto } from "./product-product-photo.model";
import { ProductReview } from "./product-review.model";
import { TransactionHistory } from "./transaction-history";
import { WorkOrder } from "./work-order.model";
import { ProductVendor } from "./product-vendor.model";
import { PurchaseOrderDetail } from "./purchase-order-detail.model";
import { ShoppingCartItem } from "./shopping-cart-item.model"
import { ProductCostHistory } from "./product-cost-history.model"

export class Product {
    productID!: number | undefined;
    title: string | undefined;
    name: string | undefined;
    description: string | undefined;
    category: string | undefined;
    price: number = 0;
    productNumber: string | undefined;
    makeFlag: boolean | undefined;
    finishedGoodsFlag: boolean | undefined;
    color?: string | undefined;
    safetyStockLevel: number = 10;
    reorderPoint: number | undefined;
    standardCost: number | undefined;
    listPrice: number | undefined;
    size?: string | undefined;
    sizeUnitMeasureCode?: string | undefined;
    weightUnitMeasureCode?: string | undefined;
    weight?: number | undefined;
    daysToManufacture: number | undefined;
    productLine?: string | undefined;
    class?: string | undefined;
    style?: string | undefined;
    productSubcategoryID?: number | undefined;
    productModelID?: number | undefined;
    sellStartDate: Date | undefined;
    sellEndDate?: Date | undefined;
    discontinuedDate?: Date | undefined;
    rowguid: string | undefined;
    image: string | undefined;
    code: number | undefined;
    modifiedDate: Date | undefined;
    quantityInStock?: number; // Add this field
    rating: {
              rate: number;
              count: number;
          }| undefined;
    unitMeasure?: UnitMeasure | undefined;
    unitMeasure1?: UnitMeasure | undefined;
    productSubcategory?: ProductSubcategory | undefined;
    productModel?: ProductModel | undefined;
    billOfMaterials?: BillOfMaterials[] | undefined;
    billOfMaterials1?: BillOfMaterials[] | undefined;
    productCostHistories?: ProductCostHistory[] | undefined;
    productDocuments?: ProductDocument[] | undefined;
    productInventories?: ProductInventory[] | undefined;
    productListPriceHistories?: ProductListPriceHistory[] | undefined;
    productProductPhotos?: ProductProductPhoto[] | undefined;
    productReviews?: ProductReview[] | undefined;
    transactionHistories?: TransactionHistory[] | undefined;
    workOrders?: WorkOrder[] | undefined;
    productVendors?: ProductVendor[] | undefined;
    purchaseOrderDetails?: PurchaseOrderDetail[] | undefined;
    shoppingCartItems?: ShoppingCartItem[] | undefined;
    specialOfferProducts?: SpecialOfferProduct[] | undefined;

}

export interface IProduct {
  productID: number | undefined;
  price: number | undefined;
  name: string | undefined;
  productNumber: string | undefined;
  makeFlag: boolean | undefined;
  finishedGoodsFlag: boolean | undefined;
  color?: string | undefined;
  safetyStockLevel: number | undefined;
  reorderPoint: number | undefined;
  standardCost: number | undefined;
  listPrice: number | undefined;
  size?: string;
  sizeUnitMeasureCode?: string;
  weightUnitMeasureCode?: string;
  weight?: number;
  daysToManufacture: number;
  productLine?: string;
  class?: string;
  style?: string;
  productSubcategoryID?: number | undefined;
  productModelID?: number | undefined;
  sellStartDate: Date | undefined;
  sellEndDate?: Date | undefined;
  discontinuedDate?: Date | undefined;
  rowguid: string | undefined;
  image: string | undefined;
  code: number | undefined;
  modifiedDate: Date | undefined;
  unitMeasure?: UnitMeasure | undefined;
  unitMeasure1?: UnitMeasure | undefined;
  productSubcategory?: ProductSubcategory | undefined;
  productModel?: ProductModel | undefined;
  billOfMaterials?: BillOfMaterials[] | undefined;
  billOfMaterials1?: BillOfMaterials[] | undefined;
  productCostHistories?: ProductCostHistory[] | undefined;
  productDocuments?: ProductDocument[] | undefined;
  productInventories?: ProductInventory[] | undefined;
  productListPriceHistories?: ProductListPriceHistory[] | undefined;
  productProductPhotos?: ProductProductPhoto[] | undefined;
  productReviews?: ProductReview[] | undefined;
  transactionHistories?: TransactionHistory[] | undefined;
  workOrders?: WorkOrder[] | undefined;
  productVendors?: ProductVendor[] | undefined;
  purchaseOrderDetails?: PurchaseOrderDetail[] | undefined;
  shoppingCartItems?: ShoppingCartItem[] | undefined;
  specialOfferProducts?: SpecialOfferProduct[] | undefined;
}
